### ISSUE TITLE
Complex Datagen

### ISSUE THREAD

**Issue by patilabhijit007** [amilkh/cs230-fer#2]
Dear Authors,
Any particular reason for converting pixels to .png file? I think it made data preprocessing bit complex.

Thanks

**Comment by amilkh** [comment]
Hi @patilabhijit007:

We wanted to use "ImageDataGenerator" from Keras.
Thus, we were able to do data augmentation on the fly and use mini-batches.

@ftcelepcikay

**Comment by patilabhijit007** [comment]
Thank you very much
